### ISSUE TITLE
14 Setting page

### ISSUE THREAD

**Issue by J-Vigen** [aau-giraf/visual-tangible-artefacts#121]
- [ ] Should have: Scenario: Toggle artefact placement method
Given the child is in the menu for settings 
When the child wants to change the artefact placement method from "drag and drop" to "click and pop" 
Then the child can toggle between the two modes: 

-  Drag and drop 
-  Click and pop 

- [ ] Could have: Scenario: Change color of artefact’s frame / background
Given the child is in the menu for settings 
And opens the settings for artefacts 
When the child wants to group different categories with colors 
Eks. Everything with a green frame / background = outdoor activities 
Then the child can......  

- [ ] Could have: Scenario: Change color of category frame / background
Given the child is in the menu for settings 
When the child wants to group different categories with colors 
Eks. Everything with a green frame / background = outdoor activities 
Then the child can drag the categories to their desired place anround the board

- [ ] Wont have: Scenario: Mute / unmute
Given the option to read artefacts and/or categories out loud is implemented 
When the child wants to toggle between the sound modes 
Then the child can toggle between the two modes: 
Mute 
Unmute 
And the system should apply the selected sound mode  

- [x] Could have: Scenario: Resize artefacts
Given the child is in the settings menu 
When the child wants changes the size of an artefact 
Then the child selects the field with the size option 
And the child changes the field’s value using a square metric in (pixels or cm) 
And the system applies the new size to the artifact 

- [x] Should have: Scenario: Add more columns to linear board
Given the child is using the linear board 
When the child wants to change the maximum number of columns 
Then the child selects the field of "linear board columns”  
And adjusts the value to the desired amount 
And the system updates the linear board to reflect the new number of columns 

- [ ] Could have: Scenario: Remove the “+” option of artefacts
Given the child is unable to use the feature of adding artifacts 
When the teacher wants to disable the option for adding artifacts 
Then the teacher should have the option to disable the “+” icon for the child 
And the child should no longer see or have access to the “+” icon for adding artifacts
